version: "3.9"  # optional since v1.27.0
services:
  influx:
    image: influxdb:2.0.8-alpine
    volumes:
    - /devops/data/staging/influxdb:/var/lib/influxdb
    environment:
    - DOCKER_INFLUXDB_INIT_USERNAME=pulu 
    - DOCKER_INFLUXDB_INIT_PASSWORD=pulu
    - DOCKER_INFLUXDB_INIT_ORG=my-org 
    - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket 
    ports:
    - 8086:8086
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
    - /devops/data/staging/mongo/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  frontend:
    image: ghcr.io/vives-projectwerk-2021/vue-frontend:latest
    ports:
    - 8080:80
  ttn:
    image: ghcr.io/vives-projectwerk-2021/ttn-listener:latest
